abstract: 'Xmldoom is a framework that allows you to bind database tables to Perl objects, a technique commonly referred to as object persistence, similar in purpose to Propel and Apache Torque'
author: David Snopek
build_requires:
  Carp: 0
  Data::Dumper: 0
  ExtUtils::MakeMaker: 6.11
  Test::Class: 0
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.62
license: gpl
name: Xmldoom
no_index:
  directory:
    - test
    - example
    - inc
    - t
requires:
  Carp: 0
  Data::Dumper: 0
  Exception::Class: 0
  Exception::Class::DBI: 0
  Exception::Class::TryCatch: 0
  File::ShareDir: 0
  File::Spec: 0
  IO::File: 0
  Roma: 0
  Scalar::Util: 0
  Template: 0
  XML::DOM: 0
  XML::GDOME: 0
  XML::SAX: 0
  XML::SAX::ExpatXS: 0
  XML::Writer: 0
  XML::Writer::String: 0
version: 0.0.9
