
//
// This file was automatically generated by xmldoom-generate 0.0.11 !
//

dojo.provide('[% ns_prefix %].[% output_basename %]');

//
// A JSON dump of the object definitions.
//

[% ns_prefix %].[% output_basename %] = '[% definition %]';

